#端口号
server:
 port: 10001

#数据源
spring:
  datasource:
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.174.103:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos地址
    alicloud: #阿里云oss用户认证信息
      access-key: LTAI5tRh6bi1Sw5q35w7AZkW
      secret-key: 1J6szYgSc6Z57INlLcHPMtVtpvfLvz
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com  #地域节点
  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #日期格式化
    time-zone: GMT+8
  thymeleaf:
    cache: false #关闭thymeleaf的缓存
  redis:
    host: 192.168.174.103 #redis地址
    port: 6379
  cache:
    type: redis #设置SpringCache缓存类型为redis
    redis:
      time-to-live: 3600000 #设置SpringCache缓存的过期时间 ms
      cache-null-values: true #是否缓存空值,防止缓存穿透
#      key-prefix: CACHE_  #key的前缀
#      use-key-prefix: false  #是否使用key前缀,默认使用


#声明MP的xml文件
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto  #主键策略
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)

#启动 mybatis 本身的 log 日志(方式二)
logging:
  level:
    com.xuyuchao.gulimall.product.dao: debug



