server:
  port: 30000

spring:
  cloud:
    alicloud: #\u963F\u91CC\u4E91oss\u7528\u6237\u8BA4\u8BC1\u4FE1\u606F
      access-key: LTAI5tRh6bi1Sw5q35w7AZkW
      secret-key: 1J6szYgSc6Z57INlLcHPMtVtpvfLvz
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com  #\u5730\u57DF\u8282\u70B9
        bucket: xuyuchao-gulimall #bucket
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos\u5730\u5740
  application:
    name: gulimall-third-party


